import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";
import Dropdownmenu from "@/components/Dropdownmenu";
import { VoiceProvider } from "@/context/VoiceContext";
import { CartProvider } from "@/context/CartContext";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "VOX MARKET",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Dropdownmenu/> */}

        <CartProvider>



          <Toaster position="top-right" />
          {children}


          <Footer />
        </CartProvider>

      </body>
    </html>
  );
}
