import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";
import Dropdownmenu from "@/components/Dropdownmenu";
import { VoiceProvider } from "@/context/VoiceContext";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "VOX MARKET",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Dropdownmenu/> */}


        <Navbar>
          <Dropdownmenu /></Navbar>

        <Toaster position="top-right" />
        {children}


        <Footer />

      </body>
    </html>
  );
}
